---
title: "Metadata summaries"
author: "Abby Lewis"
format: html
editor: visual
---

This file calculates summary statistics for the manuscript

## Table of contents

-   Step 1: Load data and packages
-   Step 2: Summary stats about dataset
-   Step 3: Concentrations in surface vs. bottom waters

## Step 1: Load data and packages

```{r setup, include=FALSE}
# Load packages
library(tidyverse)

# Load data
data <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/2220/5/8553f79eeea9a6f722fc50d733ca9a74") %>%
  filter(Focal_site) # Cleaned
metadata <- read_delim("https://pasta.lternet.edu/package/data/eml/edi/2220/5/81f003749ad039837475571390b20190") %>%
  filter(Focal_site)

# Combine
full <- data %>%
  left_join(metadata)
```

## Step 2: Summary stats about dataset

```{r summary}
sum(!is.na(data$CO2_umolL))
length(unique(data$LakeID[!is.na(data$CO2_umolL)]))
sum(!is.na(data$CH4_umolL))
length(unique(data$LakeID[!is.na(data$CH4_umolL)]))

years <- data %>%
  filter(!is.na(CH4_umolL) | !is.na(CO2_umolL)) %>%
  group_by(LakeName) %>%
  summarize(range = year(max(Date)) - year(min(Date)) + 1) %>%
  filter(!is.na(range))

# Most lakes have one year of data. Long term data is rare
median(years$range) # 1
min(year(data$Date), na.rm = T) # 1961
max(year(data$Date), na.rm = T) # 2023

# Number of unique sampling events
unique_profiles <- data %>%
  filter(!is.na(CH4_umolL) | !is.na(CO2_umolL)) %>%
  group_by(Date, LakeID, LakeName, Source) %>%
  summarize()

# Median of 4 dates per year
unique_profiles %>%
  mutate(Year = year(Date)) %>%
  group_by(Year, LakeID) %>%
  summarize(n = length(unique(Date))) %>%
  group_by(LakeID) %>%
  summarize(median = median(n)) %>%
  ungroup() %>%
  summarize(median(median))

# Median of 4 CO2 and 2 CH4 measurements
data %>%
  group_by(LakeID) %>%
  summarize(
    n_co2 = length(unique(Date[!is.na(CO2_umolL)])),
    n_ch4 = length(unique(Date[!is.na(CH4_umolL)]))
  ) %>%
  ungroup() %>%
  summarize(
    across(c(n_co2, n_ch4), \(x) median(x[x != 0]))
  )

# Lakes with one measurement
data %>%
  group_by(LakeID) %>%
  summarize(
    n_co2 = length(unique(Date[!is.na(CO2_umolL)])),
    n_ch4 = length(unique(Date[!is.na(CH4_umolL)]))
  ) %>%
  ungroup() %>%
  summarize(
    across(c(n_co2, n_ch4), \(x) sum(x == 1))
  )

unique_profiles %>%
  group_by(LakeID) %>%
  summarize(n = length(unique(Date))) %>%
  filter(n == 1) %>%
  summarize(n())
```

## Step 3: Concentrations in surface vs. bottom waters

```{r surf_bot}
layer_sum <- read_csv("../CompiledData/layer_sum_not_mean.csv")

layer_sum %>%
  select(LakeID, Source, Date, Layer, CH4_umolL, CO2_umolL) %>%
  pivot_longer(c(CH4_umolL, CO2_umolL)) %>%
  group_by(Layer, name) %>%
  summarize(
    mean = mean(value, na.rm = T),
    median = median(value, na.rm = T),
    IQR_25 = quantile(value, .25, na.rm = T),
    IQR_75 = quantile(value, .75, na.rm = T),
    min = min(value, na.rm = T),
    max = max(value, na.rm = T)
  )

max(data$CH4_umolL, na.rm = T)
max(data$CH4_umolL[!data$LakeName == "untersee"], na.rm = T)
max(data$CO2_umolL, na.rm = T)
max(data$CO2_umolL[!data$LakeName %in% c("nyos", "monoun")], na.rm = T)

epi_hypo_data <- layer_sum %>%
  group_by(LakeID, Date, Source) %>%
  mutate(
    Oxygen = ifelse(sum(!is.na(DO_mgL)) >= 1,
      mean(DO_mgL[Layer == "bot"], na.rm = T),
      NA
    )
  ) %>%
  select(LakeID, Date, Layer, CO2_umolL, CH4_umolL, Oxygen) %>%
  pivot_longer(
    cols = c(CO2_umolL, CH4_umolL), names_to = "Gas",
    values_to = "Conc"
  ) %>%
  filter(Conc >= 0) %>%
  pivot_wider(names_from = Layer, values_from = c(Conc)) %>%
  mutate(Gas = case_match(
    Gas,
    "CH4_umolL" ~ "CH[4]",
    "CO2_umolL" ~ "CO[2]"
  ))

inverse_ch4 <- epi_hypo_data %>%
  filter(Gas == "CH[4]") %>%
  filter(surf > bot)
length(unique(inverse_ch4$LakeID))

epi_hypo_data %>%
  mutate(DO_level = ifelse(Oxygen > 1, "Oxic", "Anoxic")) %>%
  filter(!is.na(DO_level)) %>%
  pivot_longer(c(surf, bot), values_to = "Conc", names_to = "Layer") %>%
  group_by(Gas, Layer, DO_level) %>%
  summarize(med = median(Conc, na.rm = T))
```
