---
title: "Molar concentrations"
format: html
editor: visual
---

This file plots molar concentrations of both gases.

## Table of contents

-   Step 1: Load data and packages
-   Step 2: Format data
-   Step 3: Plot molar concentrations

## Step 1: Load data and packages

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(sf)
library(spdep)
library(gstat)

# Load data
data <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/2220/5/8553f79eeea9a6f722fc50d733ca9a74?key=n9dYnNE5ReoA53SyzOCNgcPzLZA") %>%
  filter(Focal_site) # Cleaned
metadata <- read_delim("https://pasta.lternet.edu/package/data/eml/edi/2220/5/81f003749ad039837475571390b20190?key=n9dYnNE5ReoA53SyzOCNgcPzLZA") %>%
  filter(Focal_site)
layer_sum <- read_csv("../CompiledData/layer_sum.csv")
```

## Step 2: Format data

```{r}
layer_means <- layer_sum %>%
  pivot_longer(cols = CO2_umolL:CH4_umolL) %>%
  group_by(LakeID, name, Layer, Date) %>%
  filter(!is.na(value)) %>%
  mutate(
    value = mean(value, na.rm = T),
    yday = yday(Date),
    year = year(Date)
  ) %>%
  group_by(LakeID, name, Layer) %>%
  summarize(
    value = mean(value, na.rm = T)
  )

metadata_by_lake <- metadata %>%
  group_by(LakeID) %>%
  mutate(
    across(
      c(TrophicStatus, StratificationRegime),
      \(x) ifelse(is.na(x), unique(x[!is.na(x)]), x)
    ),
    Osgood = MeanDepth_m / sqrt(SurfaceArea_km2)
  ) %>%
  summarize(
    across(
      c(
        MaximumDepth_m,
        SurfaceArea_km2,
        Chla_ugL_mean,
        TP_ugL_mean,
        DOC_mgL_mean,
        MeanDepth_m,
        Osgood,
        Latitude,
        Longitude
      ),
      \(x) mean(x, na.rm = T)
    ),
    across(
      c(
        TrophicStatus,
        StratificationRegime,
        LakeType
      ),
      \(x) paste(unique(x), collapse = " AND ")
    )
  )

all <- layer_means %>%
  left_join(metadata_by_lake)
```

```{r}
all

pts <- all %>%
  filter(
    !is.na(value),
    !is.na(Latitude),
    !is.na(Longitude)
  ) %>%
  st_as_sf(
    coords = c("Longitude", "Latitude"),
    crs = 4326
  )

distances <- seq(
  100,
  5000,
  by = 1000
)

moran_results <- pts %>%
  filter(
    !is.na(value),
    !is.na(Layer),
    !is.na(name)
  ) %>%
  group_by(Layer, name) %>%
  group_modify(~ {

    # Extract coordinates for this Layer × name group
    coords <- st_coordinates(.x)

    map_dfr(
      distances,
      function(d) {

        nb <- dnearneigh(
          coords,
          d1 = 0,
          d2 = d,
          longlat = TRUE
        )

        lw <- nb2listw(
          nb,
          style = "W",
          zero.policy = TRUE
        )
        
        n_subgraphs = n.comp.nb(nb)$nc

        test <- moran.test(
          .x$value,
          lw,
          zero.policy = TRUE
        )

        tibble(
          distance_km = d,
          moran_I = unname(test$estimate[1]),
          p_value = test$p.value,
          subgraphs = n_subgraphs,
          n = nrow(.x),
          n_neighbors = sum(card(nb) > 0)
        )
      }
    )
  }) %>%
  ungroup()

ggplot(
  moran_results,
  aes(
    x = distance_km,
    y = moran_I
  )
) +
  geom_line() +
  geom_point() +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  ggh4x::facet_grid2(
    Layer ~ name, scales = "free_y", independent = "y"
  ) +
  egg::theme_article() +
  theme(
    legend.position = "right",
    panel.grid.major = element_line(color = "grey90", size = 0.5),
    panel.grid.minor = element_line(color = "grey95", size = 0.25)
  )
  

ggplot(
  moran_results,
  aes(
    x = distance_km,
    y = n_neighbors
  )
) +
  geom_line() +
  facet_grid(Layer ~ name)

ggplot(
  moran_results,
  aes(
    x = distance_km,
    y = subgraphs
  )
) +
  geom_line() +
  facet_grid(Layer ~ name)
```
